"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Skin = exports.Mouth = exports.Eyebrow = exports.Eyes = exports.GraphicOnClothes = exports.FabricColour = exports.Clothes = exports.HairColour = exports.FacialHair = exports.Accessories = exports.AvatarStyle = exports.Hair = void 0;
var Hair;
(function (Hair) {
    Hair["NoHair"] = "NoHair";
    Hair["Eyepatch"] = "Eyepatch";
    Hair["Hat"] = "Hat";
    Hair["Hijab"] = "Hijab";
    Hair["Turban"] = "Turban";
    Hair["WinterHat1"] = "WinterHat1";
    Hair["WinterHat2"] = "WinterHat2";
    Hair["WinterHat3"] = "WinterHat3";
    Hair["WinterHat4"] = "WinterHat4";
    Hair["LongHairBigHair"] = "LongHairBigHair";
    Hair["LongHairBob"] = "LongHairBob";
    Hair["LongHairBun"] = "LongHairBun";
    Hair["LongHairCurly"] = "LongHairCurly";
    Hair["LongHairCurvy"] = "LongHairCurvy";
    Hair["LongHairDreads"] = "LongHairDreads";
    Hair["LongHairFrida"] = "LongHairFrida";
    Hair["LongHairFro"] = "LongHairFro";
    Hair["LongHairFroBand"] = "LongHairFroBand";
    Hair["LongHairNotTooLong"] = "LongHairNotTooLong";
    Hair["LongHairShavedSides"] = "LongHairShavedSides";
    Hair["LongHairMiaWallace"] = "LongHairMiaWallace";
    Hair["LongHairStraight"] = "LongHairStraight";
    Hair["LongHairStraight2"] = "LongHairStraight2";
    Hair["LongHairStraightStrand"] = "LongHairStraightStrand";
    Hair["ShortHairDreads01"] = "ShortHairDreads01";
    Hair["ShortHairDreads02"] = "ShortHairDreads02";
    Hair["ShortHairFrizzle"] = "ShortHairFrizzle";
    Hair["ShortHairShaggyMullet"] = "ShortHairShaggyMullet";
    Hair["ShortHairShortCurly"] = "ShortHairShortCurly";
    Hair["ShortHairShortFlat"] = "ShortHairShortFlat";
    Hair["ShortHairShortRound"] = "ShortHairShortRound";
    Hair["ShortHairShortWaved"] = "ShortHairShortWaved";
    Hair["ShortHairSides"] = "ShortHairSides";
    Hair["ShortHairTheCaesar"] = "ShortHairTheCaesar";
    Hair["ShortHairTheCaesarSidePart"] = "ShortHairTheCaesarSidePart";
})(Hair = exports.Hair || (exports.Hair = {}));
var AvatarStyle;
(function (AvatarStyle) {
    AvatarStyle["Circle"] = "Circle";
    AvatarStyle["Transparent"] = "Transparent";
})(AvatarStyle = exports.AvatarStyle || (exports.AvatarStyle = {}));
var Accessories;
(function (Accessories) {
    Accessories["Blank"] = "Blank";
    Accessories["Kurt"] = "Kurt";
    Accessories["Prescription01"] = "Prescription01";
    Accessories["Prescription02"] = "Prescription02";
    Accessories["Round"] = "Round";
    Accessories["Sunglasses"] = "Sunglasses";
    Accessories["Wayfarers"] = "Wayfarers ";
})(Accessories = exports.Accessories || (exports.Accessories = {}));
var FacialHair;
(function (FacialHair) {
    FacialHair["Blank"] = "Blank";
    FacialHair["BeardMedium"] = "BeardMedium";
    FacialHair["BeardLight"] = "BeardLight";
    FacialHair["BeardMagestic"] = "BeardMagestic";
    FacialHair["MoustacheFancy"] = "MoustacheFancy";
    FacialHair["MoustacheMagnum"] = "MoustacheMagnum";
})(FacialHair = exports.FacialHair || (exports.FacialHair = {}));
var HairColour;
(function (HairColour) {
    HairColour["Auburn"] = "Auburn";
    HairColour["Black"] = "Black";
    HairColour["Blonde"] = "Blonde";
    HairColour["BlondeGolden"] = "BlondeGolden";
    HairColour["Brown"] = "Brown";
    HairColour["BrownDark"] = "BrownDark";
    HairColour["Platinum"] = "Platinum";
    HairColour["Red"] = "Red";
})(HairColour = exports.HairColour || (exports.HairColour = {}));
var Clothes;
(function (Clothes) {
    Clothes["BlazerShirt"] = "BlazerShirt";
    Clothes["BlazerSweater"] = "BlazerSweater";
    Clothes["CollarSweater"] = "CollarSweater";
    Clothes["GraphicShirt"] = "GraphicShirt";
    Clothes["Hoodie"] = "Hoodie";
    Clothes["Overall"] = "Overall";
    Clothes["ShirtCrewNeck"] = "ShirtCrewNeck";
    Clothes["ShirtScoopNeck"] = "ShirtScoopNeck";
    Clothes["ShirtVNeck"] = "ShirtVNeck";
})(Clothes = exports.Clothes || (exports.Clothes = {}));
var FabricColour;
(function (FabricColour) {
    FabricColour["Black"] = "Black";
    FabricColour["Blue01"] = "Blue01";
    FabricColour["Blue02"] = "Blue02";
    FabricColour["Blue03"] = "Blue03";
    FabricColour["Gray01"] = "Gray01";
    FabricColour["Gray02"] = "Gray02";
    FabricColour["Heather"] = "Heather";
    FabricColour["PastelBlue"] = "PastelBlue";
    FabricColour["PastelGreen"] = "PastelGreen";
    FabricColour["PastelOrange"] = "PastelOrange";
    FabricColour["PastelRed"] = "PastelRed";
    FabricColour["PastelYellow"] = "PastelYellow";
    FabricColour["Pink"] = "Pink";
    FabricColour["Red"] = "Red";
    FabricColour["White"] = "White";
})(FabricColour = exports.FabricColour || (exports.FabricColour = {}));
var GraphicOnClothes;
(function (GraphicOnClothes) {
    GraphicOnClothes["Bat"] = "Bat";
    GraphicOnClothes["Cumbia"] = "Cumbia";
    GraphicOnClothes["Deer"] = "Deer";
    GraphicOnClothes["Diamond"] = "Diamond";
    GraphicOnClothes["Hola"] = "Hola";
    GraphicOnClothes["Pizza"] = "Pizza";
    GraphicOnClothes["Resist"] = "Resist";
    GraphicOnClothes["Selena"] = "Selena";
    GraphicOnClothes["Bear"] = "Bear";
    GraphicOnClothes["SkullOutline"] = "SkullOutline";
    GraphicOnClothes["Skull"] = "Skull";
})(GraphicOnClothes = exports.GraphicOnClothes || (exports.GraphicOnClothes = {}));
var Eyes;
(function (Eyes) {
    Eyes["Close"] = "Close";
    Eyes["Cry"] = "Cry";
    Eyes["Default"] = "Default";
    Eyes["Dizzy"] = "Dizzy";
    Eyes["EyeRoll"] = "EyeRoll";
    Eyes["Happy"] = "Happy";
    Eyes["Hearts"] = "Hearts";
    Eyes["Side"] = "Side";
    Eyes["Squint"] = "Squint";
    Eyes["Surprised"] = "Surprised";
    Eyes["Wink"] = "Wink";
    Eyes["WinkWacky"] = "WinkWacky";
})(Eyes = exports.Eyes || (exports.Eyes = {}));
var Eyebrow;
(function (Eyebrow) {
    Eyebrow["Angry"] = "Angry";
    Eyebrow["AngryNatural"] = "AngryNatural";
    Eyebrow["Default"] = "Default";
    Eyebrow["DefaultNatural"] = "DefaultNatural";
    Eyebrow["FlatNatural"] = "FlatNatural";
    Eyebrow["RaisedExcited"] = "RaisedExcited";
    Eyebrow["RaisedExcitedNatural"] = "RaisedExcitedNatural";
    Eyebrow["SadConcerned"] = "SadConcerned";
    Eyebrow["SadConcernedNatural"] = "SadConcernedNatural";
    Eyebrow["UnibrowNatural"] = "UnibrowNatural";
    Eyebrow["UpDown"] = "UpDown";
    Eyebrow["UpDownNatural"] = "UpDownNatural";
})(Eyebrow = exports.Eyebrow || (exports.Eyebrow = {}));
var Mouth;
(function (Mouth) {
    Mouth["Concerned"] = "Concerned";
    Mouth["Default"] = "Default";
    Mouth["Disbelief"] = "Disbelief";
    Mouth["Eating"] = "Eating";
    Mouth["Grimace"] = "Grimace";
    Mouth["Sad"] = "Sad";
    Mouth["ScreamOpen"] = "ScreamOpen";
    Mouth["Serious"] = "Serious";
    Mouth["Smile"] = "Smile";
    Mouth["Tongue"] = "Tongue";
    Mouth["Twinkle"] = "Twinkle";
    Mouth["Vomit"] = "Vomit";
})(Mouth = exports.Mouth || (exports.Mouth = {}));
var Skin;
(function (Skin) {
    Skin["Tanned"] = "Tanned";
    Skin["Yellow"] = "Yellow";
    Skin["Pale"] = "Pale";
    Skin["Light"] = "Light";
    Skin["Brown"] = "Brown";
    Skin["DarkBrown"] = "DarkBrown";
    Skin["Black"] = "Black";
})(Skin = exports.Skin || (exports.Skin = {}));
